### ISSUE TITLE
no completion after a space 

### ISSUE THREAD

**Issue by kraxli** [idanarye/vim-dutyl#23]
Hi, in the code bellow I cannot complete `wri<tab>` for e.g. `writeln` 

```dlang
import std.stdio;
void main(){
wri<tab>
}
```
However when I use 
```dlang
import io = std.stdio;
void main(){
io.wri<tab>
}
```
`io.wri<tab>` brings up the completion suggestions. 

Is there an option I need to set to get completion on spaces?

Thanks

**Comment by idanarye** [comment]
This looks like a [DCD](https://github.com/Hackerpilot/DCD) problem - please open a ticket over there. But before you do that, make sure you have the latests version of DCD, because I just checked with version `v0.7.3 d8253402188913aed3d00d2240ca54b61b6ff7e7` and I got autocompletion in both scenarios.

**Comment by kraxli** [comment]
It worked (again) after a restart :-| . Thanks and sorry the too early post!
